version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  terraform-plan:
    docker:
      - image: hashicorp/terraform:1.0.0
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Terraform Init
          command: |
            cd environments/dev
            terraform init
      - run:
          name: Terraform Plan
          command: |
            cd environments/dev
            terraform plan -var-file=../../secrets/terraform.dev.tfvars -out=tfplan
      - persist_to_workspace:
          root: environments/dev
          paths:
            - tfplan

  terraform-apply:
    docker:
      - image: hashicorp/terraform:1.0.0
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - attach_workspace:
          at: environments/dev
      - run:
          name: Terraform Apply
          command: |
            cd environments/dev
            terraform apply -auto-approve tfplan

workflows:
  version: 2
  terraform-workflow:
    jobs:
      - terraform-plan:
          context: aws-credentials
      - hold-for-approval:
          type: approval
          requires:
            - terraform-plan
      - terraform-apply:
          requires:
            - hold-for-approval
          context: aws-credentials