version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  plan-apply:
    docker:
      - image: hashicorp/terraform:1.0.0
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Terraform Init
          command: |
            cd environments/dev
            terraform init
      - run:
          name: Terraform Plan
          command: |
            cd environments/dev
            terraform plan -var-file=../../secrets/terraform.dev.tfvars -out=tfplan
      - persist_to_workspace:
          root: environments/dev
          paths:
            - tfplan

  apply:
    docker:
      - image: hashicorp/terraform:1.0.0
    steps:
      - checkout
      - aws-cli/setup
      - attach_workspace:
          at: environments/dev
      - run:
          name: Terraform Apply
          command: |
            cd environments/dev
            terraform apply tfplan

workflows:
  version: 2
  plan-apply:
    jobs:
      - plan-apply:
          context: aws
      - hold-for-approval:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-for-approval
          context: aws