version: 2.1

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.3.6
        environment:
          AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY
          AWS_SECRET_ACCESS_KEY: AWS_SECRET_KEY
    working_directory: ~/repo

jobs:
  install_aws_cli:
    docker:
      - image: hashicorp/terraform:1.3.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache python3 py3-pip curl unzip
            pip3 install awscli

  plan:
    docker:
      - image: hashicorp/terraform:1.3.6
    steps:
      - checkout
      - run:
          name: List secrets directory
          command: ls -la secrets
      - setup_remote_docker
      - run:
          name: Set up Terraform
          command: |
            terraform init
            terraform workspace select dev || terraform workspace new dev
      - run:
          name: Terraform Plan
          command: terraform plan -var-file=secrets/terraform.dev.tfvars


workflows:
  version: 2
  terraform:
    jobs:
      - install_aws_cli
      - plan:
          requires:
            - install_aws_cli
