version: 2.1

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.3.6
        environment:
          AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY
          AWS_SECRET_ACCESS_KEY: AWS_SECRET_KEY
    working_directory: ~/repo

jobs:
  plan:
    executor: terraform
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install AWS CLI
          command: |
            apt-get update && apt-get install -y unzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Set up Terraform
          command: |
            terraform init
            terraform workspace select staging || terraform workspace new staging
      - run:
          name: Decrypt secrets
          command: sops -d secrets/secrets.yaml > secrets/decrypted_secrets.yaml
      - run:
          name: Terraform Plan
          command: terraform plan -var-file="secrets/decrypted_secrets.yaml"

  apply:
    executor: terraform
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install AWS CLI
          command: |
            apt-get update && apt-get install -y unzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Set up Terraform
          command: |
            terraform init
            terraform workspace select staging || terraform workspace new staging
      - run:
          name: Decrypt secrets
          command: sops -d secrets/secrets.yaml > secrets/decrypted_secrets.yaml
      - run:
          name: Terraform Apply
          command: terraform apply -var-file="secrets/decrypted_secrets.yaml" -auto-approve

workflows:
  version: 2
  terraform:
    jobs:
      - plan
      - apply:
          requires:
            - plan
